import type { ReactNode } from 'react'

import type { Metadata } from 'next'

import { Nunito } from 'next/font/google'

import '@/app/globals.css'
import { Providers } from '@/app/providers'

const nunito = Nunito({
   variable: '--font-nunito',
   subsets: ['cyrillic'],
   weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: ReactNode
}>) {
   return (
      <html lang={'en'} suppressHydrationWarning>
         <body
            className={`
               ${nunito.variable}
               antialiased
            `}
         >
            <Providers>{children}</Providers>
         </body>
      </html>
   )
}
