/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
   '/categories': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Get all categories */
      get: operations['getCategories']
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
   '/products': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Get all products */
      get: operations['getProducts']
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
   '/products/{slug}': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Get product by slug */
      get: operations['getProductBySlug']
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
   '/ingredients': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Get all ingredients */
      get: {
         parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
         }
         requestBody?: never
         responses: {
            /** @description List of ingredients */
            200: {
               headers: {
                  [name: string]: unknown
               }
               content: {
                  'application/json': components['schemas']['IngredientsList']
               }
            }
         }
      }
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
}
export type webhooks = Record<string, never>
export interface components {
   schemas: {
      Category: {
         /** Format: int32 */
         id: number
         /** @example zavtrak */
         slug: string
         /** @example Завтрак */
         name: string
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         createdAt: string
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         updatedAt: string
      }
      ProductItem: {
         /** Format: int32 */
         id: number
         price: number
         /**
          * Format: uri
          * @example https://example.com/images/coffee.png
          */
         imageUrl: string | null
         type: number | null
         size: number | null
         /** Format: int32 */
         productId: number
      }
      Product: {
         /** Format: int32\ */
         id: number
         /** @example latte */
         slug: string
         /** @example Latte */
         name: string
         /** @example A freshly brewed cup of coffee */
         description: string | null
         /**
          * Format: uri
          * @example https://example.com/images/coffee.png
          */
         imageUrl: string | null
         /**
          * @example HIT
          * @enum {string}
          */
         status: 'NEW' | 'HIT' | 'REGULAR'
         category: {
            /** Format: int32 */
            id: number
            slug: string
            /** @example Breakfast */
            name: string
         }
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         createdAt: string
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         updatedAt: string
         items: components['schemas']['ProductItem'][]
      }
      ProductsList: components['schemas']['Product'][]
      Error: {
         message: string
         code: string
      }
      Ingredient: {
         /** Format: int32 */
         id: number
         /** @example bacon */
         name: string
         price: number
         /**
          * Format: uri
          * @example https://example.com/images/bacon.png
          */
         imageUrl: string | null
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         createdAt: string
         /**
          * Format: date-time
          * @example 2025-08-14T12:34:56Z
          */
         updatedAt: string
      }
      IngredientsList: components['schemas']['Ingredient'][]
   }
   responses: {
      /** @description Resource not found */
      NotFoundError: {
         headers: {
            [name: string]: unknown
         }
         content: {
            'application/json': components['schemas']['Error']
         }
      }
   }
   parameters: never
   requestBodies: never
   headers: never
   pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
   getCategories: {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      requestBody?: never
      responses: {
         /** @description List of categories */
         200: {
            headers: {
               [name: string]: unknown
            }
            content: {
               'application/json': components['schemas']['Category'][]
            }
         }
      }
   }
   getProducts: {
      parameters: {
         query?: {
            name?: string
         }
         header?: never
         path?: never
         cookie?: never
      }
      requestBody?: never
      responses: {
         /** @description List of products */
         200: {
            headers: {
               [name: string]: unknown
            }
            content: {
               'application/json': components['schemas']['ProductsList']
            }
         }
      }
   }
   getProductBySlug: {
      parameters: {
         query?: never
         header?: never
         path: {
            slug: string
         }
         cookie?: never
      }
      requestBody?: never
      responses: {
         /** @description Product */
         200: {
            headers: {
               [name: string]: unknown
            }
            content: {
               'application/json': components['schemas']['Product']
            }
         }
         404: components['responses']['NotFoundError']
      }
   }
}
