/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
   '/categories': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Получение категорий */
      get: operations['getCategories']
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
   '/products': {
      parameters: {
         query?: never
         header?: never
         path?: never
         cookie?: never
      }
      /** Получение продуктов */
      get: operations['getProducts']
      put?: never
      post?: never
      delete?: never
      options?: never
      head?: never
      patch?: never
      trace?: never
   }
}
export type webhooks = Record<string, never>
export interface components {
   schemas: {
      User: {
         /** Format: uuid */
         id: string
         /** Format: email */
         email: string
         /** @example Андреев Андрей Андреевич */
         fullName: string
         /** @enum {string} */
         role: 'USER' | 'ADMIN'
         provider: string | null
         providerId: string | null
         isVerified: boolean
         /** Format: date-time */
         createdAt: string
         /** Format: date-time */
         updatedAt: string
      }
      CategoryShort: {
         id: components['schemas']['Cuid']
         /** @example Пиццы */
         name: string
         /** @example piccy */
         slug: string
      }
      Category: components['schemas']['CategoryShort'] & {
         description: string | null
         /** Format: date-time */
         createdAt: string
         /** Format: date-time */
         updatedAt: string
      }
      Size: {
         id: components['schemas']['Cuid']
         /** @example 20 см */
         name: string
      }
      Ingredient: {
         id: components['schemas']['Cuid']
         /** @example Традиционное тесто 20 */
         name: string
         /** @example Традиционное */
         displayName: string | null
         /** Format: uri */
         thumbnailUrl: string
         /** Format: date-time */
         createdAt: string
         /** Format: date-time */
         updatedAt: string
      }
      Product: {
         id: components['schemas']['Cuid']
         /** @example Пепперони */
         name: string
         /** @example pepperoni */
         slug: string
         description: string | null
         /** Format: uri */
         imageUrl: string | null
         /** @enum {string} */
         status: 'DEFAULT' | 'NEW' | 'HIT' | 'ARCHIVED'
         /** Format: int32 */
         maxCountPerOrder: number | null
         /**
          * Format: double
          * @default null
          */
         price: number | null
         /** Format: date-time */
         createdAt: string
         /** Format: date-time */
         updatedAt: string
         category: components['schemas']['CategoryShort']
         traits: {
            /** @default false */
            vegan: boolean
            /** @default false */
            spicy: boolean
            /** @default false */
            forChildren: boolean
         }
         variations: components['schemas']['ProductVariation'][]
      }
      ProductVariation: {
         id: components['schemas']['Cuid']
         isDefault: boolean
         /** Format: double */
         price: number
         /** Format: uri */
         imageUrl: string | null
         size: components['schemas']['Size']
         foodValue: {
            /** Format: double */
            calories: number
            /** Format: double */
            proteins: number
            /** Format: double */
            fats: number
            /** Format: double */
            carbohydrates: number
            /** Format: double */
            weight: number
         }
         ingredients: components['schemas']['ProductVariationIngredient'][]
         toppings: {
            id: components['schemas']['Cuid']
            name: string
            /** Format: uri */
            imageUrl: string | null
            /** Format: double */
            price: number
         }[]
      }
      ProductVariationIngredient: {
         ingredientId: components['schemas']['Cuid']
         /** @enum {string} */
         choiceType: 'NONE' | 'SINGLE' | 'MULTIPLE'
         /** @default false */
         isBasic: boolean
         details: {
            name: string
            displayName: string | null
            /** Format: uri */
            thumbnailUrl: string | null
         }
      }
      /** @description CUID identifier */
      Cuid: string
      ErrorMessage: {
         message: string
         /** Format: int32 */
         code: number
      }
      ErrorFieldMessages: {
         messages: {
            /** @example password */
            field: string
            /** @example Пароль - обязательное поле! */
            message: string
         }[]
         /** Format: int32 */
         code: number
      }
      Error: components['schemas']['ErrorMessage'] | components['schemas']['ErrorFieldMessages']
   }
   responses: {
      /** @description Bad Request */
      400: {
         headers: {
            [name: string]: unknown
         }
         content: {
            'application/json': components['schemas']['Error']
         }
      }
      /** @description Unauthorized */
      401: {
         headers: {
            [name: string]: unknown
         }
         content: {
            'application/json': components['schemas']['Error']
         }
      }
      /** @description Resource not found */
      404: {
         headers: {
            [name: string]: unknown
         }
         content: {
            'application/json': components['schemas']['Error']
         }
      }
   }
   parameters: never
   requestBodies: never
   headers: never
   pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
   getCategories: {
      parameters: {
         query?: {
            /** @description Показывать только те категории, по которым был создан хотя бы один продукт */
            onlyWithProducts?: boolean
         }
         header?: never
         path?: never
         cookie?: never
      }
      requestBody?: never
      responses: {
         /** @description Список категорий */
         200: {
            headers: {
               [name: string]: unknown
            }
            content: {
               'application/json': components['schemas']['Category'][]
            }
         }
      }
   }
   getProducts: {
      parameters: {
         query?: {
            /** @description Поиск по названии продукта */
            name?: string
            /**
             * @description Строка, задающая поле для сортировки и направление.   **Формат:** `fieldName-direction` или `fieldName.subFieldName-direction`
             *     **Доступные направления:**   - `asc` — по возрастанию   - `desc` — по убыванию
             *     **Примеры:**   - `name-desc` — сортировка по названию (по убыванию)   - `created-asc` — сортировка по дате создания (по возрастанию)   - `author.name-asc` — сортировка по имени автора (по возрастанию)
             */
            orderBy?:
               | null
               | 'status-asc'
               | 'status-desc'
               | 'price-asc'
               | 'price-desc'
               | 'createdAt-asc'
               | 'createdAt-desc'
               | 'updatedAt-asc'
               | 'updatedAt-desc'
         }
         header?: never
         path?: never
         cookie?: never
      }
      requestBody?: never
      responses: {
         /** @description Список продуктов */
         200: {
            headers: {
               [name: string]: unknown
            }
            content: {
               'application/json': components['schemas']['Product'][]
            }
         }
      }
   }
}
