openapi: 3.0.4
info:
  title: Next Pizza API
  description: API для пет проекта - Next Pizza. Этакий "Клон" DodoPizza.
  version: 1.0.0
  contact:
    name: Philian73
    email: philian73@gmail.com

servers:
  - url: /api
    description: Локальная разработка
  - url: https://api.nextpizza.ru/api
    description: Релиз

tags:
  - name: category
  - name: product
  - name: cart

paths:
  /categories:
    get:
      tags: [category]
      summary: Получение категорий
      operationId: getCategories
      parameters:
        - name: onlyWithProducts
          description: Показывать только те категории, по которым был создан хотя бы один продукт
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Список категорий
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/Category'

  /products:
    get:
      tags: [product]
      summary: Получение продуктов
      operationId: getProducts
      parameters:
        - name: name
          description: Поиск по названии продукта
          in: query
          required: false
          schema:
            type: string
        - name: orderBy
          in: query
          required: false
          description: >
            Строка, задающая поле для сортировки и направление.  
            **Формат:** `fieldName-direction` или `fieldName.subFieldName-direction`  

            **Доступные направления:**  
            - `asc` — по возрастанию  
            - `desc` — по убыванию  

            **Примеры:**  
            - `name-desc` — сортировка по названию (по убыванию)  
            - `created-asc` — сортировка по дате создания (по возрастанию)  
            - `author.name-asc` — сортировка по имени автора (по возрастанию)  
          schema:
            type: string
            enum: [null, status-asc, status-desc, price-asc, price-desc, createdAt-asc, createdAt-desc, updatedAt-asc, updatedAt-desc]
      responses:
        '200':
          description: Список продуктов
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/Product'

  /cart:
    get:
      tags: [cart]
      summary: Получение корзины
      operationId: getCart
      responses:
        '200':
          description: Корзина
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /cart/cart-item:
    patch:
      tags: [cart]
      summary: Обновление элемента корзины
      operationId: updateCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [cartItemId, quantity]
              properties:
                cartItemId:
                  $ref: '#/components/schemas/Cuid'
                quantity:
                  type: integer
                  format: int32
                  minimum: 1
                toppingIds:
                  type: array
                  items:
                    $ref: '#/components/schemas/Cuid'
                removedIngredientIds:
                  type: array
                  items:
                    $ref: '#/components/schemas/Cuid'
      responses:
        '200':
          description: Обновленная корзина
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

components:
  schemas:
    User:
      type: object
      required: [id, email, fullName, role, provider, providerId, isVerified, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        fullName:
          type: string
          example: Андреев Андрей Андреевич
        role:
          type: string
          enum: [USER, ADMIN]
        provider:
          type: string
          nullable: true
        providerId:
          type: string
          nullable: true
        isVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CategoryShort:
      type: object
      required: [id, name, slug]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        name:
          type: string
          example: 'Пиццы'
        slug:
          type: string
          example: 'piccy'
    Category:
      allOf:
        - $ref: '#/components/schemas/CategoryShort'
        - type: object
          required: [description, createdAt, updatedAt]
          properties:
            description:
              type: string
              nullable: true
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    Size:
      type: object
      required: [id, name]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        name:
          type: string
          example: '20 см'

    Ingredient:
      type: object
      required: [id, name, displayName, thumbnailUrl, createdAt, updatedAt]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        name:
          type: string
          example: 'Традиционное тесто 20'
        displayName:
          type: string
          nullable: true
          example: 'Традиционное'
        thumbnailUrl:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Topping:
      type: object
      required: [id, name, thumbnailUrl, price]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        name:
          type: string
        thumbnailUrl:
          type: string
          format: uri
          nullable: true
        price:
          type: number
          format: double

    Product:
      type: object
      required: [id, name, slug, description, imageUrl, status, maxCountPerOrder, price, createdAt, updatedAt, category, traits, variations]
      properties:
        id:
              $ref: '#/components/schemas/Cuid'
        name:
              type: string
              example: 'Пепперони'
        slug:
              type: string
              example: 'pepperoni'
        description:
              type: string
              nullable: true
        imageUrl:
              type: string
              format: uri
              nullable: true
        status:
              type: string
              enum: [ DEFAULT, NEW, HIT, ARCHIVED ]
        maxCountPerOrder:
              type: integer
              format: int32
              nullable: true
        price:
              type: number
              format: double
              nullable: true
              default: null
        createdAt:
              type: string
              format: date-time
        updatedAt:
              type: string
              format: date-time
        category:
              $ref: '#/components/schemas/CategoryShort'
        traits:
              type: object
              properties:
                vegan:
                  type: boolean
                  default: false
                spicy:
                  type: boolean
                  default: false
                forChildren:
                  type: boolean
                  default: false
        variations:
              type: array
              minItems: 0
              items:
                $ref: '#/components/schemas/ProductVariation'

    ProductVariation:
      type: object
      required: [id, isDefault, price, imageUrl, size, foodValue, ingredients, toppings]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        isDefault:
          type: boolean
        price:
          type: number
          format: double
        imageUrl:
          type: string
          format: uri
          nullable: true
        size:
          $ref: '#/components/schemas/Size'
        foodValue:
          $ref: '#/components/schemas/ProductVariationFoodValue'
        ingredients:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/ProductVariationIngredient'
        toppings:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/Topping'

    ProductVariationIngredient:
      type: object
      required: [ingredientId, choiceType, isBasic, details]
      properties:
        ingredientId:
          $ref: '#/components/schemas/Cuid'
        choiceType:
          type: string
          enum: [NONE, SINGLE, MULTIPLE]
        isBasic:
          type: boolean
          default: false
        details:
          type: object
          required: [name, displayName, thumbnailUrl]
          properties:
            name:
              type: string
            displayName:
              type: string
              nullable: true
            thumbnailUrl:
              type: string
              format: uri
              nullable: true

    ProductVariationFoodValue:
      type: object
      required: [ calories, proteins, fats, carbohydrates, weight ]
      properties:
        calories:
          type: number
          format: double
        proteins:
          type: number
          format: double
        fats:
          type: number
          format: double
        carbohydrates:
          type: number
          format: double
        weight:
          type: number
          format: double

    Cart:
      type: object
      required: [totalAmount, items]
      properties:
        totalAmount:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'

    CartItem:
      type: object
      required: [id, product, variationId, details, quantity, imageUrl, toppings, removedIngredients, subtotal]
      properties:
        id:
          $ref: '#/components/schemas/Cuid'
        product:
          type: object
          required: [id, slug, name]
          properties:
            id:
              $ref: '#/components/schemas/Cuid'
            slug:
              type: string
            name:
              type: string
        variationId:
          $ref: '#/components/schemas/Cuid'
        quantity:
          type: integer
          format: int32
        imageUrl:
          type: string
          format: uri
          nullable: true
        toppings:
          type: array
          minItems: 0
          items:
            type: object
            required: [id, name, price]
            properties:
              id:
                $ref: '#/components/schemas/Cuid'
              name:
                type: string
              price:
                type: number
                format: double
        removedIngredients:
          type: array
          minItems: 0
          items:
            type: object
            required: [id, name, displayName]
            properties:
              id:
                $ref: '#/components/schemas/Cuid'
              name:
                type: string
              displayName:
                type: string
                nullable: true
        subtotal:
          type: number
          format: double


    Cuid:
      type: string
      description: "CUID identifier"
      pattern: '^c[a-z0-9]{24}$'

    ErrorMessage:
      type: object
      required: [message, code]
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
    ErrorFieldMessages:
      type: object
      required: [messages, code]
      properties:
        messages:
          type: array
          items:
            type: object
            required: [field, message]
            properties:
              field:
                type: string
                example: "password"
              message:
                type: string
                example: "Пароль - обязательное поле!"
        code:
          type: integer
          format: int32
    Error:
      oneOf:
        - $ref: '#/components/schemas/ErrorMessage'
        - $ref: '#/components/schemas/ErrorFieldMessages'

  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'